### ISSUE TITLE
[Proposal] Drop jQuery for Zepto.js and Velocity.js

### ISSUE THREAD

**Issue by ghost** [KiraLT/Bjax#2]
I saw that `No jQuery dependency` is listed under feature plans.

Do you want to go full vanila JavaScript or did you consider to drop jQuery for http://zeptojs.com/ and http://julian.com/research/velocity/?

**Comment by KiraLT** [comment]
I am planning go full vanilla for (better performance?) and for websites without jQuery. Maybe it's a good idea to create build with http://zeptojs.com/ and http://julian.com/research/velocity/ for websites without jQuery, because it's easier than full vanilla. Also they have similar API, so I don't need create 2 separated versions.
